name: PHPUnit

on:
  push:
    branches:
      - main
      - develop
      - 'release/[0-9]+.[0-9]+*'
      - 'hotfix/[0-9]+.[0-9]+*'
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml'
      - 'tests/**'
      - '.github/workflows/phpunit.yml'
  pull_request:
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml'
      - 'tests/**'
      - '.github/workflows/phpunit.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpunit:
    name: "PHPUnit: PHP ${{ matrix.php_version }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php_version: [ '8.1', '8.2', '8.3' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          coverage: none
          tools: composer

      - name: Validate Composer configuration
        run: composer validate --no-check-publish

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: '--prefer-dist'

      - name: Run PHPUnit
        run: composer test
