name: Build Plugin Pre-Release

on:
  release:
    types: [ prereleased ]

jobs:
  build:
    name: Build Plugin Artifact
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: composer

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: '--no-dev --prefer-dist --optimize-autoloader'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Build frontend assets
        run: |
          npm ci
          npm run build

      - name: Generate plugin artifact
        run: |
          rsync -rc --exclude-from="$GITHUB_WORKSPACE/.distignore" "$GITHUB_WORKSPACE/" release/ --delete --delete-excluded
          cd "${GITHUB_WORKSPACE}/release" || exit
          zip -r "${GITHUB_WORKSPACE}/perform.zip" .

      - name: Upload release asset
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ github.workspace }}/perform.zip
